inputs:
  version:
    required: true
runs:
  steps:
    - name: Build nuget packages
      run: dotnet pack --configuration Release --include-source --include-symbols --nologo --no-restore --output .artifacts/packages --verbosity normal -p:PackageVersion=$inputs.version *.sln